# Generated by Django 3.0.11 on 2021-07-12 13:07

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('folder_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAction',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('template', models.TextField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edually.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.FilePathField(path='./content', recursive=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edually.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CourseExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('enrolled_count', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edually.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edually.Semester')),
                ('student', models.ManyToManyField(to='edually.Student')),
            ],
            options={
                'unique_together': {('semester', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('send_mail', models.BooleanField(default=False)),
                ('send_doodle', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('state', django_fsm.FSMField(default='new', max_length=50)),
                ('courseExecution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edually.CourseExecution')),
                ('course_action', models.ManyToManyField(to='edually.CourseAction')),
                ('course_content', models.ManyToManyField(to='edually.CourseContent')),
            ],
            options={
                'unique_together': {('courseExecution_id', 'week')},
            },
        ),
    ]
