# Generated by Django 3.0.11 on 2021-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edually', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='folder_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
