# Generated by Django 3.0.11 on 2021-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edually', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='path',
            field=models.FilePathField(path='C:/Users/Susi/Documents/Beuth/SoSe21/EBE/content/mathe'),
        ),
    ]
