# Generated by Django 3.0.11 on 2021-07-12 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edually', '0002_auto_20210712_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseweek',
            name='week_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
