# Generated by Django 3.0.11 on 2021-07-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edually', '0003_courseweek_week_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseweek',
            name='course_action',
            field=models.ManyToManyField(blank=True, to='edually.CourseAction'),
        ),
        migrations.AlterField(
            model_name='courseweek',
            name='course_content',
            field=models.ManyToManyField(blank=True, to='edually.CourseContent'),
        ),
    ]
