# Generated by Django 3.0.11 on 2021-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edually', '0004_auto_20210714_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseweek',
            name='course_action',
            field=models.ManyToManyField(blank=True, to='edually.CourseAction', verbose_name='Course templates'),
        ),
        migrations.AlterField(
            model_name='courseweek',
            name='send_doodle',
            field=models.BooleanField(default=False, verbose_name='Poll is needed this week.'),
        ),
        migrations.AlterField(
            model_name='courseweek',
            name='send_mail',
            field=models.BooleanField(default=False, verbose_name='E-Mail needs to be send this week.'),
        ),
    ]
