# Generated by Django 3.0.11 on 2021-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edually', '0006_auto_20210714_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseweek',
            name='notes',
            field=models.TextField(blank=True, max_length=26500, null=True),
        ),
    ]
